### ISSUE TITLE
Auction House Error with Addon

### ISSUE THREAD

**Issue by GinJeanie** [NekoNova/ItemPreviewImproved#2]
...Addons\itempreviewimprovedex\ItemPreviewImproved.lua:616: attempt to index local 'itemCurr' (a nil value)
stack trace:
    ...Addons\itempreviewimprovedex\ItemPreviewImproved.lua:616: in function <...Addons\itempreviewimprovedex\ItemPreviewImproved.lua:597>
    (tail call): ?
    ui\MarketplaceAuction\MarketplaceAuction.lua:799: in function <ui\MarketplaceAuction\MarketplaceAuction.lua:781>

Looks like this:
http://i61.tinypic.com/fnqq0x.jpg

Only the marketplace auction addon is acting up, but it's pointing to an error in both, or caused by IPIex

**Comment by coding-red-panda** [comment]
I'll see if I can reproduce this over the weekend and figure out what is causing the problem.
I cannot guarantee a fix, with Drop 5 coming up and potentially other things being broken, as the source code for ItemPreviewPreviewEx is cluncky.

**Comment by coding-red-panda** [comment]
Should be fixed in latest version now.
